project:
  type: website
  output-dir: _site

website:
  title: "Reddit as an Early Warning System"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: methodology.qmd
        text: Methodology
      - href: eda.qmd
        text: EDA
      - href: nlp.qmd
        text: NLP
      - href: ml.qmd
        text: ML

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-overflow: wrap
